import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { ProjectOptions } from '../prompts.js';

/**
 * Generate a coloured per-project Makefile in the project root.
 * Tailored to the chosen frontend (nextjs/tanstack) and backend (hono/laravel/symfony).
 */
export async function generateMakefile(
  projectDir: string,
  options: ProjectOptions,
): Promise<void> {
  const isPhp = options.backend === 'laravel' || options.backend === 'symfony';
  const isLaravel = options.backend === 'laravel';
  const isSymfony = options.backend === 'symfony';
  const isHono = options.backend === 'hono';
  const frontPort = options.frontend === 'nextjs' ? '3300' : '3301';
  const apiPort = isLaravel ? '8002' : isSymfony ? '8001' : '3333';
  const frontLabel = options.frontend === 'nextjs' ? 'Next.js' : 'TanStack';
  const apiLabel = isLaravel ? 'Laravel' : isSymfony ? 'Symfony' : 'Hono';

  // ── Per-stack command snippets ──────────────────────────────────────────
  const installApi = isPhp
    ? '@cd apps/api && composer install --no-interaction'
    : '@cd apps/api && bun install';

  const devApi = isLaravel
    ? `@cd apps/api && php artisan serve --port=${apiPort}`
    : isSymfony
      ? `@cd apps/api && symfony server:start --port=${apiPort} --no-tls`
      : '@cd apps/api && bun run dev';

  const devWeb = '@cd apps/web && bun run dev';

  const testApi = isLaravel
    ? '@cd apps/api && php artisan test'
    : isSymfony
      ? '@cd apps/api && php bin/phpunit'
      : '@cd apps/api && bun test';

  const lintApi = isPhp
    ? '@cd apps/api && composer lint 2>/dev/null || true'
    : '@cd apps/api && bun run lint 2>/dev/null || true';

  const dbResetApi = isLaravel
    ? `@cd apps/api && php artisan migrate:fresh --seed --force
\t@echo "  $(C_GREEN)✓$(C_RESET) Laravel DB reset"`
    : isSymfony
      ? `@cd apps/api && rm -f var/data_dev.db
\t@cd apps/api && php bin/console doctrine:migrations:migrate --no-interaction
\t@cd apps/api && php bin/console doctrine:fixtures:load --no-interaction
\t@echo "  $(C_GREEN)✓$(C_RESET) Symfony DB reset"`
      : `@cd apps/api && rm -f data.db
\t@cd apps/api && bun run db:push
\t@cd apps/api && bun run db:seed
\t@echo "  $(C_GREEN)✓$(C_RESET) Hono DB reset"`;

  const content = `# ============================================================================
# ${options.projectName} — Makefile
# Frontend: ${frontLabel} (:${frontPort})  ·  Backend: ${apiLabel} (:${apiPort})
# Generated by create-headless-app
# ============================================================================

C_RESET   := \\033[0m
C_BOLD    := \\033[1m
C_DIM     := \\033[2m
C_GREEN   := \\033[32m
C_CYAN    := \\033[36m
C_YELLOW  := \\033[33m
C_RED     := \\033[31m
C_MAGENTA := \\033[35m
C_BLUE    := \\033[34m

.PHONY: help install dev dev-web dev-api build lint test \\
        db-reset clean \\
        docker-up docker-down docker-logs docker-build docker-prod

# ============================================================================
# Help (default target)
# ============================================================================

help:
\t@echo ""
\t@echo "  $(C_BOLD)$(C_CYAN)━━━ ${options.projectName} ━━━$(C_RESET)"
\t@echo "  $(C_DIM)${frontLabel} :${frontPort}  +  ${apiLabel} :${apiPort}$(C_RESET)"
\t@echo ""
\t@echo "  $(C_BOLD)Setup$(C_RESET)"
\t@echo "  $(C_GREEN)install$(C_RESET)         Install all deps $(C_DIM)(web + api)$(C_RESET)"
\t@echo "  $(C_GREEN)build$(C_RESET)           Build frontend"
\t@echo "  $(C_GREEN)clean$(C_RESET)           Remove node_modules + build output"
\t@echo ""
\t@echo "  $(C_BOLD)Dev$(C_RESET)"
\t@echo "  $(C_GREEN)dev$(C_RESET)             Run web + api in parallel $(C_DIM)(needs concurrently)$(C_RESET)"
\t@echo "  $(C_GREEN)dev-web$(C_RESET)         Frontend only $(C_DIM):${frontPort}$(C_RESET)"
\t@echo "  $(C_GREEN)dev-api$(C_RESET)         Backend only $(C_DIM):${apiPort}$(C_RESET)"
\t@echo ""
\t@echo "  $(C_BOLD)QA$(C_RESET)"
\t@echo "  $(C_GREEN)lint$(C_RESET)            Lint web + api"
\t@echo "  $(C_GREEN)test$(C_RESET)            Run all tests"
\t@echo ""
\t@echo "  $(C_BOLD)Database$(C_RESET)"
\t@echo "  $(C_GREEN)db-reset$(C_RESET)        Reset DB + seed $(C_DIM)(${apiLabel})$(C_RESET)"
\t@echo ""
\t@echo "  $(C_BOLD)Docker$(C_RESET)"
\t@echo "  $(C_GREEN)docker-up$(C_RESET)       Start dev stack $(C_DIM)(compose.yml)$(C_RESET)"
\t@echo "  $(C_GREEN)docker-down$(C_RESET)     Stop & remove containers"
\t@echo "  $(C_GREEN)docker-logs$(C_RESET)     Tail container logs"
\t@echo "  $(C_GREEN)docker-build$(C_RESET)    Rebuild images"
\t@echo "  $(C_GREEN)docker-prod$(C_RESET)     Run prod stack $(C_DIM)(compose.prod.yml)$(C_RESET)"
\t@echo ""
\t@echo "  $(C_BOLD)$(C_YELLOW)Quick start:$(C_RESET)"
\t@echo "    make install"
\t@echo "    make db-reset"
\t@echo "    make dev"
\t@echo ""

# ============================================================================
# Setup
# ============================================================================

install:
\t@echo "  $(C_CYAN)►$(C_RESET) Installing $(C_BOLD)web$(C_RESET) deps..."
\t@cd apps/web && bun install
\t@echo "  $(C_CYAN)►$(C_RESET) Installing $(C_BOLD)api$(C_RESET) deps..."
\t${installApi}
\t@echo "  $(C_GREEN)✓$(C_RESET) Dependencies installed"

build:
\t@echo "  $(C_CYAN)►$(C_RESET) Building frontend..."
\t@cd apps/web && bun run build
\t@echo "  $(C_GREEN)✓$(C_RESET) Build complete"

clean:
\t@echo "  $(C_YELLOW)►$(C_RESET) Cleaning..."
\t@rm -rf apps/web/node_modules apps/web/.next apps/web/.output apps/web/dist
\t@rm -rf apps/api/node_modules apps/api/vendor apps/api/var/cache
\t@echo "  $(C_GREEN)✓$(C_RESET) Clean"

# ============================================================================
# Dev
# ============================================================================

dev:
\t@echo "  $(C_CYAN)►$(C_RESET) $(C_BOLD)${frontLabel}$(C_RESET) $(C_DIM):${frontPort}$(C_RESET)  +  $(C_BOLD)${apiLabel}$(C_RESET) $(C_DIM):${apiPort}$(C_RESET)"
\t@bunx concurrently -n web,api -c cyan,${isHono ? 'green' : isLaravel ? 'magenta' : 'yellow'} \\
\t\t"$(MAKE) --no-print-directory dev-web" \\
\t\t"$(MAKE) --no-print-directory dev-api"

dev-web:
\t${devWeb}

dev-api:
\t${devApi}

# ============================================================================
# QA
# ============================================================================

lint:
\t@echo "  $(C_CYAN)━━━ Lint web ━━━$(C_RESET)"
\t@cd apps/web && bun run lint 2>/dev/null || true
\t@echo "  $(C_CYAN)━━━ Lint api ━━━$(C_RESET)"
\t${lintApi}
\t@echo "  $(C_GREEN)✓$(C_RESET) Lint passed"

test:
\t@echo "  $(C_CYAN)━━━ Test web ━━━$(C_RESET)"
\t@cd apps/web && bun test 2>/dev/null || true
\t@echo "  $(C_CYAN)━━━ Test api ━━━$(C_RESET)"
\t${testApi}
\t@echo "  $(C_GREEN)✓$(C_RESET) Tests passed"

# ============================================================================
# Database
# ============================================================================

db-reset:
\t@echo "  $(C_YELLOW)►$(C_RESET) Resetting ${apiLabel} database..."
\t${dbResetApi}
\t@echo "  $(C_DIM)admin@example.com / Admin1234!$(C_RESET)"
\t@echo "  $(C_DIM)user@example.com  / User1234!$(C_RESET)"

# ============================================================================
# Docker
# ============================================================================

docker-up:
\t@echo "  $(C_CYAN)►$(C_RESET) Starting Docker stack..."
\t@docker compose -f compose.yml up -d
\t@echo "  $(C_GREEN)✓$(C_RESET) Stack up — $(C_BOLD)http://localhost:${frontPort}$(C_RESET)"

docker-down:
\t@echo "  $(C_YELLOW)►$(C_RESET) Stopping Docker stack..."
\t@docker compose -f compose.yml down

docker-logs:
\t@docker compose -f compose.yml logs -f --tail=100

docker-build:
\t@echo "  $(C_CYAN)►$(C_RESET) Building images..."
\t@docker compose -f compose.yml build
\t@echo "  $(C_GREEN)✓$(C_RESET) Images built"

docker-prod:
\t@echo "  $(C_MAGENTA)►$(C_RESET) Starting $(C_BOLD)prod$(C_RESET) stack..."
\t@docker compose -f compose.prod.yml up -d
\t@echo "  $(C_GREEN)✓$(C_RESET) Prod stack up"
`;

  await fs.writeFile(path.join(projectDir, 'Makefile'), content, 'utf-8');
}
