<?php

declare(strict_types=1);

namespace App\Http\Controllers\Auth;

use BetterAuth\Laravel\Services\BetterAuthManager;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;

/**
 * Auth Controller - Generated by BetterAuth.
 *
 * This controller provides authentication endpoints for your API.
 * You can customize the responses or add your business logic here.
 *
 * @example To customize the registration response, modify the register() method
 * @example To add additional validation, update the validate() calls
 */
final class AuthController extends Controller
{
    public function __construct(
        private readonly BetterAuthManager $auth,
    ) {}

    /**
     * Register a new user.
     *
     * @POST /auth/register
     *
     * @param  Request  $request
     * @return JsonResponse
     *
     * @throws ValidationException
     */
    public function register(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'email' => ['required', 'email', 'max:255'],
            'password' => ['required', 'string', 'min:8', 'max:255'],
            'name' => ['sometimes', 'string', 'max:255'],
            'avatar' => ['sometimes', 'string', 'max:500'],
        ]);

        // Check if email already exists
        if ($this->auth->emailExists($validated['email'])) {
            throw ValidationException::withMessages([
                'email' => ['This email is already registered.'],
            ]);
        }

        $result = $this->auth->signUp($validated);

        return response()->json([
            'message' => 'Registration successful',
            'user' => $this->formatUser($result['user']),
            'access_token' => $result['access_token'],
            'refresh_token' => $result['refresh_token'],
            'token_type' => 'Bearer',
            'expires_in' => $result['expires_in'],
        ], 201);
    }

    /**
     * Authenticate a user.
     *
     * @POST /auth/login
     *
     * @param  Request  $request
     * @return JsonResponse
     *
     * @throws ValidationException
     */
    public function login(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required', 'string'],
        ]);

        try {
            $result = $this->auth->signIn($validated['email'], $validated['password']);

            return response()->json([
                'message' => 'Login successful',
                'user' => $this->formatUser($result['user']),
                'access_token' => $result['access_token'],
                'refresh_token' => $result['refresh_token'],
                'token_type' => 'Bearer',
                'expires_in' => $result['expires_in'],
            ]);

        } catch (\Exception $e) {
            throw ValidationException::withMessages([
                'email' => ['The provided credentials are incorrect.'],
            ]);
        }
    }

    /**
     * Get current authenticated user.
     *
     * @GET /auth/me
     *
     * @param  Request  $request
     * @return JsonResponse
     */
    public function me(Request $request): JsonResponse
    {
        $user = Auth::guard('betterauth')->user();

        if ($user === null) {
            return response()->json([
                'message' => 'Unauthenticated',
            ], 401);
        }

        return response()->json([
            'user' => $user,
        ]);
    }

    /**
     * Refresh access token.
     *
     * @POST /auth/refresh
     *
     * @param  Request  $request
     * @return JsonResponse
     */
    public function refresh(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'refresh_token' => ['required', 'string'],
        ]);

        try {
            $result = $this->auth->refresh($validated['refresh_token']);

            return response()->json([
                'message' => 'Token refreshed',
                'access_token' => $result['access_token'],
                'refresh_token' => $result['refresh_token'],
                'token_type' => 'Bearer',
                'expires_in' => $result['expires_in'],
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'message' => 'Invalid refresh token',
                'error' => 'token_invalid',
            ], 401);
        }
    }

    /**
     * Logout and revoke refresh token.
     *
     * @POST /auth/logout
     *
     * @param  Request  $request
     * @return JsonResponse
     */
    public function logout(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'refresh_token' => ['required', 'string'],
        ]);

        $this->auth->signOut($validated['refresh_token']);

        return response()->json([
            'message' => 'Logged out successfully',
        ]);
    }

    /**
     * Revoke all tokens for the authenticated user.
     *
     * @POST /auth/revoke-all
     *
     * @param  Request  $request
     * @return JsonResponse
     */
    public function revokeAll(Request $request): JsonResponse
    {
        $user = Auth::guard('betterauth')->user();

        if ($user === null) {
            return response()->json([
                'message' => 'Unauthenticated',
            ], 401);
        }

        $userId = (string) $user->getAuthIdentifier();
        $this->auth->revokeAll($userId);

        return response()->json([
            'message' => 'All tokens revoked',
        ]);
    }

    /**
     * Update user password.
     *
     * @PUT /auth/password
     *
     * @param  Request  $request
     * @return JsonResponse
     *
     * @throws ValidationException
     */
    public function updatePassword(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'current_password' => ['required', 'string'],
            'password' => ['required', 'string', 'min:8', 'max:255', 'confirmed'],
        ]);

        $user = Auth::guard('betterauth')->user();

        if ($user === null) {
            return response()->json([
                'message' => 'Unauthenticated',
            ], 401);
        }

        $userId = (string) $user->getAuthIdentifier();

        try {
            $updated = $this->auth->updatePassword(
                $userId,
                $validated['current_password'],
                $validated['password']
            );

            if (! $updated) {
                throw ValidationException::withMessages([
                    'current_password' => ['The current password is incorrect.'],
                ]);
            }

            return response()->json([
                'message' => 'Password updated successfully',
            ]);

        } catch (\Exception $e) {
            throw ValidationException::withMessages([
                'current_password' => ['The current password is incorrect.'],
            ]);
        }
    }

    /**
     * Format user array for JSON response.
     *
     * @param  array<string, mixed>  $user
     * @return array<string, mixed>
     */
    private function formatUser(array $user): array
    {
        // Remove sensitive fields
        unset($user['password'], $user['remember_token']);

        return $user;
    }
}
