/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as SaasIndexRouteImport } from './routes/saas/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SupportCRouteImport } from './routes/support/c'
import { Route as SupportAgentRouteImport } from './routes/support/agent'
import { Route as SupportTicketIdRouteImport } from './routes/support/$ticketId'
import { Route as ShopOrdersRouteImport } from './routes/shop/orders'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopAdminRouteImport } from './routes/shop/admin'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as SaasUsageRouteImport } from './routes/saas/usage'
import { Route as SaasTeamRouteImport } from './routes/saas/team'
import { Route as SaasSettingsRouteImport } from './routes/saas/settings'
import { Route as SaasOnboardingRouteImport } from './routes/saas/onboarding'
import { Route as SaasBillingRouteImport } from './routes/saas/billing'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTodosRouteImport } from './routes/dashboard/todos'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardPostsRouteImport } from './routes/dashboard/posts'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard/permissions'
import { Route as DashboardHelpRouteImport } from './routes/dashboard/help'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as SupportAgentIndexRouteImport } from './routes/support/agent/index'
import { Route as ShopAdminIndexRouteImport } from './routes/shop/admin/index'
import { Route as SupportCIdRouteImport } from './routes/support/c/$id'
import { Route as SupportAuthResetPasswordRouteImport } from './routes/support/auth/reset-password'
import { Route as SupportAuthForgotPasswordRouteImport } from './routes/support/auth/forgot-password'
import { Route as SupportAgentRatingsRouteImport } from './routes/support/agent/ratings'
import { Route as SupportAgentCannedRouteImport } from './routes/support/agent/canned'
import { Route as ShopOrdersIdRouteImport } from './routes/shop/orders/$id'
import { Route as ShopCategoriesCategoryRouteImport } from './routes/shop/categories/$category'
import { Route as ShopAuthResetPasswordRouteImport } from './routes/shop/auth/reset-password'
import { Route as ShopAuthForgotPasswordRouteImport } from './routes/shop/auth/forgot-password'
import { Route as ShopAdminReviewsRouteImport } from './routes/shop/admin/reviews'
import { Route as ShopAdminProductsRouteImport } from './routes/shop/admin/products'
import { Route as ShopAdminOrdersRouteImport } from './routes/shop/admin/orders'
import { Route as ShopAdminInventoryRouteImport } from './routes/shop/admin/inventory'
import { Route as ShopAdminCustomersRouteImport } from './routes/shop/admin/customers'
import { Route as ShopAdminCategoriesRouteImport } from './routes/shop/admin/categories'
import { Route as ShopAdminAnalyticsRouteImport } from './routes/shop/admin/analytics'
import { Route as SaasAuthResetPasswordRouteImport } from './routes/saas/auth/reset-password'
import { Route as SaasAuthForgotPasswordRouteImport } from './routes/saas/auth/forgot-password'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const SaasIndexRoute = SaasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaasRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SupportCRoute = SupportCRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => SupportRoute,
} as any)
const SupportAgentRoute = SupportAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SupportRoute,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAdminRoute = ShopAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const SaasUsageRoute = SaasUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SaasRoute,
} as any)
const SaasTeamRoute = SaasTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SaasRoute,
} as any)
const SaasSettingsRoute = SaasSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SaasRoute,
} as any)
const SaasOnboardingRoute = SaasOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SaasRoute,
} as any)
const SaasBillingRoute = SaasBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SaasRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTodosRoute = DashboardTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const SupportAgentIndexRoute = SupportAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportAgentRoute,
} as any)
const ShopAdminIndexRoute = ShopAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopAdminRoute,
} as any)
const SupportCIdRoute = SupportCIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupportCRoute,
} as any)
const SupportAuthResetPasswordRoute =
  SupportAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => SupportRoute,
  } as any)
const SupportAuthForgotPasswordRoute =
  SupportAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => SupportRoute,
  } as any)
const SupportAgentRatingsRoute = SupportAgentRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => SupportAgentRoute,
} as any)
const SupportAgentCannedRoute = SupportAgentCannedRouteImport.update({
  id: '/canned',
  path: '/canned',
  getParentRoute: () => SupportAgentRoute,
} as any)
const ShopOrdersIdRoute = ShopOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopOrdersRoute,
} as any)
const ShopCategoriesCategoryRoute = ShopCategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAuthResetPasswordRoute = ShopAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAuthForgotPasswordRoute = ShopAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAdminReviewsRoute = ShopAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminProductsRoute = ShopAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminOrdersRoute = ShopAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminInventoryRoute = ShopAdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminCustomersRoute = ShopAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminCategoriesRoute = ShopAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminAnalyticsRoute = ShopAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShopAdminRoute,
} as any)
const SaasAuthResetPasswordRoute = SaasAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => SaasRoute,
} as any)
const SaasAuthForgotPasswordRoute = SaasAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => SaasRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/saas': typeof SaasRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/onboarding': typeof SaasOnboardingRoute
  '/saas/settings': typeof SaasSettingsRoute
  '/saas/team': typeof SaasTeamRoute
  '/saas/usage': typeof SaasUsageRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/admin': typeof ShopAdminRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRouteWithChildren
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/agent': typeof SupportAgentRouteWithChildren
  '/support/c': typeof SupportCRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/saas/': typeof SaasIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/saas/auth/forgot-password': typeof SaasAuthForgotPasswordRoute
  '/saas/auth/reset-password': typeof SaasAuthResetPasswordRoute
  '/shop/admin/analytics': typeof ShopAdminAnalyticsRoute
  '/shop/admin/categories': typeof ShopAdminCategoriesRoute
  '/shop/admin/customers': typeof ShopAdminCustomersRoute
  '/shop/admin/inventory': typeof ShopAdminInventoryRoute
  '/shop/admin/orders': typeof ShopAdminOrdersRoute
  '/shop/admin/products': typeof ShopAdminProductsRoute
  '/shop/admin/reviews': typeof ShopAdminReviewsRoute
  '/shop/auth/forgot-password': typeof ShopAuthForgotPasswordRoute
  '/shop/auth/reset-password': typeof ShopAuthResetPasswordRoute
  '/shop/categories/$category': typeof ShopCategoriesCategoryRoute
  '/shop/orders/$id': typeof ShopOrdersIdRoute
  '/support/agent/canned': typeof SupportAgentCannedRoute
  '/support/agent/ratings': typeof SupportAgentRatingsRoute
  '/support/auth/forgot-password': typeof SupportAuthForgotPasswordRoute
  '/support/auth/reset-password': typeof SupportAuthResetPasswordRoute
  '/support/c/$id': typeof SupportCIdRoute
  '/shop/admin/': typeof ShopAdminIndexRoute
  '/support/agent/': typeof SupportAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/onboarding': typeof SaasOnboardingRoute
  '/saas/settings': typeof SaasSettingsRoute
  '/saas/team': typeof SaasTeamRoute
  '/saas/usage': typeof SaasUsageRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRouteWithChildren
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/c': typeof SupportCRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/saas': typeof SaasIndexRoute
  '/shop': typeof ShopIndexRoute
  '/support': typeof SupportIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/saas/auth/forgot-password': typeof SaasAuthForgotPasswordRoute
  '/saas/auth/reset-password': typeof SaasAuthResetPasswordRoute
  '/shop/admin/analytics': typeof ShopAdminAnalyticsRoute
  '/shop/admin/categories': typeof ShopAdminCategoriesRoute
  '/shop/admin/customers': typeof ShopAdminCustomersRoute
  '/shop/admin/inventory': typeof ShopAdminInventoryRoute
  '/shop/admin/orders': typeof ShopAdminOrdersRoute
  '/shop/admin/products': typeof ShopAdminProductsRoute
  '/shop/admin/reviews': typeof ShopAdminReviewsRoute
  '/shop/auth/forgot-password': typeof ShopAuthForgotPasswordRoute
  '/shop/auth/reset-password': typeof ShopAuthResetPasswordRoute
  '/shop/categories/$category': typeof ShopCategoriesCategoryRoute
  '/shop/orders/$id': typeof ShopOrdersIdRoute
  '/support/agent/canned': typeof SupportAgentCannedRoute
  '/support/agent/ratings': typeof SupportAgentRatingsRoute
  '/support/auth/forgot-password': typeof SupportAuthForgotPasswordRoute
  '/support/auth/reset-password': typeof SupportAuthResetPasswordRoute
  '/support/c/$id': typeof SupportCIdRoute
  '/shop/admin': typeof ShopAdminIndexRoute
  '/support/agent': typeof SupportAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/saas': typeof SaasRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/onboarding': typeof SaasOnboardingRoute
  '/saas/settings': typeof SaasSettingsRoute
  '/saas/team': typeof SaasTeamRoute
  '/saas/usage': typeof SaasUsageRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/admin': typeof ShopAdminRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRouteWithChildren
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/agent': typeof SupportAgentRouteWithChildren
  '/support/c': typeof SupportCRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/saas/': typeof SaasIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/saas/auth/forgot-password': typeof SaasAuthForgotPasswordRoute
  '/saas/auth/reset-password': typeof SaasAuthResetPasswordRoute
  '/shop/admin/analytics': typeof ShopAdminAnalyticsRoute
  '/shop/admin/categories': typeof ShopAdminCategoriesRoute
  '/shop/admin/customers': typeof ShopAdminCustomersRoute
  '/shop/admin/inventory': typeof ShopAdminInventoryRoute
  '/shop/admin/orders': typeof ShopAdminOrdersRoute
  '/shop/admin/products': typeof ShopAdminProductsRoute
  '/shop/admin/reviews': typeof ShopAdminReviewsRoute
  '/shop/auth/forgot-password': typeof ShopAuthForgotPasswordRoute
  '/shop/auth/reset-password': typeof ShopAuthResetPasswordRoute
  '/shop/categories/$category': typeof ShopCategoriesCategoryRoute
  '/shop/orders/$id': typeof ShopOrdersIdRoute
  '/support/agent/canned': typeof SupportAgentCannedRoute
  '/support/agent/ratings': typeof SupportAgentRatingsRoute
  '/support/auth/forgot-password': typeof SupportAuthForgotPasswordRoute
  '/support/auth/reset-password': typeof SupportAuthResetPasswordRoute
  '/support/c/$id': typeof SupportCIdRoute
  '/shop/admin/': typeof ShopAdminIndexRoute
  '/support/agent/': typeof SupportAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/saas'
    | '/shop'
    | '/support'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/help'
    | '/dashboard/permissions'
    | '/dashboard/posts'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/oauth/callback'
    | '/saas/billing'
    | '/saas/onboarding'
    | '/saas/settings'
    | '/saas/team'
    | '/saas/usage'
    | '/shop/$slug'
    | '/shop/admin'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/orders'
    | '/support/$ticketId'
    | '/support/agent'
    | '/support/c'
    | '/dashboard/'
    | '/saas/'
    | '/shop/'
    | '/support/'
    | '/api/ai/chat'
    | '/api/v1/$'
    | '/saas/auth/forgot-password'
    | '/saas/auth/reset-password'
    | '/shop/admin/analytics'
    | '/shop/admin/categories'
    | '/shop/admin/customers'
    | '/shop/admin/inventory'
    | '/shop/admin/orders'
    | '/shop/admin/products'
    | '/shop/admin/reviews'
    | '/shop/auth/forgot-password'
    | '/shop/auth/reset-password'
    | '/shop/categories/$category'
    | '/shop/orders/$id'
    | '/support/agent/canned'
    | '/support/agent/ratings'
    | '/support/auth/forgot-password'
    | '/support/auth/reset-password'
    | '/support/c/$id'
    | '/shop/admin/'
    | '/support/agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/help'
    | '/dashboard/permissions'
    | '/dashboard/posts'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/oauth/callback'
    | '/saas/billing'
    | '/saas/onboarding'
    | '/saas/settings'
    | '/saas/team'
    | '/saas/usage'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/orders'
    | '/support/$ticketId'
    | '/support/c'
    | '/dashboard'
    | '/saas'
    | '/shop'
    | '/support'
    | '/api/ai/chat'
    | '/api/v1/$'
    | '/saas/auth/forgot-password'
    | '/saas/auth/reset-password'
    | '/shop/admin/analytics'
    | '/shop/admin/categories'
    | '/shop/admin/customers'
    | '/shop/admin/inventory'
    | '/shop/admin/orders'
    | '/shop/admin/products'
    | '/shop/admin/reviews'
    | '/shop/auth/forgot-password'
    | '/shop/auth/reset-password'
    | '/shop/categories/$category'
    | '/shop/orders/$id'
    | '/support/agent/canned'
    | '/support/agent/ratings'
    | '/support/auth/forgot-password'
    | '/support/auth/reset-password'
    | '/support/c/$id'
    | '/shop/admin'
    | '/support/agent'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/saas'
    | '/shop'
    | '/support'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/help'
    | '/dashboard/permissions'
    | '/dashboard/posts'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/oauth/callback'
    | '/saas/billing'
    | '/saas/onboarding'
    | '/saas/settings'
    | '/saas/team'
    | '/saas/usage'
    | '/shop/$slug'
    | '/shop/admin'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/orders'
    | '/support/$ticketId'
    | '/support/agent'
    | '/support/c'
    | '/dashboard/'
    | '/saas/'
    | '/shop/'
    | '/support/'
    | '/api/ai/chat'
    | '/api/v1/$'
    | '/saas/auth/forgot-password'
    | '/saas/auth/reset-password'
    | '/shop/admin/analytics'
    | '/shop/admin/categories'
    | '/shop/admin/customers'
    | '/shop/admin/inventory'
    | '/shop/admin/orders'
    | '/shop/admin/products'
    | '/shop/admin/reviews'
    | '/shop/auth/forgot-password'
    | '/shop/auth/reset-password'
    | '/shop/categories/$category'
    | '/shop/orders/$id'
    | '/support/agent/canned'
    | '/support/agent/ratings'
    | '/support/auth/forgot-password'
    | '/support/auth/reset-password'
    | '/support/c/$id'
    | '/shop/admin/'
    | '/support/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SaasRoute: typeof SaasRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/saas/': {
      id: '/saas/'
      path: '/'
      fullPath: '/saas/'
      preLoaderRoute: typeof SaasIndexRouteImport
      parentRoute: typeof SaasRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/support/c': {
      id: '/support/c'
      path: '/c'
      fullPath: '/support/c'
      preLoaderRoute: typeof SupportCRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/agent': {
      id: '/support/agent'
      path: '/agent'
      fullPath: '/support/agent'
      preLoaderRoute: typeof SupportAgentRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/admin': {
      id: '/shop/admin'
      path: '/admin'
      fullPath: '/shop/admin'
      preLoaderRoute: typeof ShopAdminRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/saas/usage': {
      id: '/saas/usage'
      path: '/usage'
      fullPath: '/saas/usage'
      preLoaderRoute: typeof SaasUsageRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/team': {
      id: '/saas/team'
      path: '/team'
      fullPath: '/saas/team'
      preLoaderRoute: typeof SaasTeamRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/settings': {
      id: '/saas/settings'
      path: '/settings'
      fullPath: '/saas/settings'
      preLoaderRoute: typeof SaasSettingsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/onboarding': {
      id: '/saas/onboarding'
      path: '/onboarding'
      fullPath: '/saas/onboarding'
      preLoaderRoute: typeof SaasOnboardingRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/billing': {
      id: '/saas/billing'
      path: '/billing'
      fullPath: '/saas/billing'
      preLoaderRoute: typeof SaasBillingRouteImport
      parentRoute: typeof SaasRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/todos': {
      id: '/dashboard/todos'
      path: '/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardTodosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/support/agent/': {
      id: '/support/agent/'
      path: '/'
      fullPath: '/support/agent/'
      preLoaderRoute: typeof SupportAgentIndexRouteImport
      parentRoute: typeof SupportAgentRoute
    }
    '/shop/admin/': {
      id: '/shop/admin/'
      path: '/'
      fullPath: '/shop/admin/'
      preLoaderRoute: typeof ShopAdminIndexRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/support/c/$id': {
      id: '/support/c/$id'
      path: '/$id'
      fullPath: '/support/c/$id'
      preLoaderRoute: typeof SupportCIdRouteImport
      parentRoute: typeof SupportCRoute
    }
    '/support/auth/reset-password': {
      id: '/support/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/support/auth/reset-password'
      preLoaderRoute: typeof SupportAuthResetPasswordRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/auth/forgot-password': {
      id: '/support/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/support/auth/forgot-password'
      preLoaderRoute: typeof SupportAuthForgotPasswordRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/agent/ratings': {
      id: '/support/agent/ratings'
      path: '/ratings'
      fullPath: '/support/agent/ratings'
      preLoaderRoute: typeof SupportAgentRatingsRouteImport
      parentRoute: typeof SupportAgentRoute
    }
    '/support/agent/canned': {
      id: '/support/agent/canned'
      path: '/canned'
      fullPath: '/support/agent/canned'
      preLoaderRoute: typeof SupportAgentCannedRouteImport
      parentRoute: typeof SupportAgentRoute
    }
    '/shop/orders/$id': {
      id: '/shop/orders/$id'
      path: '/$id'
      fullPath: '/shop/orders/$id'
      preLoaderRoute: typeof ShopOrdersIdRouteImport
      parentRoute: typeof ShopOrdersRoute
    }
    '/shop/categories/$category': {
      id: '/shop/categories/$category'
      path: '/categories/$category'
      fullPath: '/shop/categories/$category'
      preLoaderRoute: typeof ShopCategoriesCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/auth/reset-password': {
      id: '/shop/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/shop/auth/reset-password'
      preLoaderRoute: typeof ShopAuthResetPasswordRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/auth/forgot-password': {
      id: '/shop/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/shop/auth/forgot-password'
      preLoaderRoute: typeof ShopAuthForgotPasswordRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/admin/reviews': {
      id: '/shop/admin/reviews'
      path: '/reviews'
      fullPath: '/shop/admin/reviews'
      preLoaderRoute: typeof ShopAdminReviewsRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/products': {
      id: '/shop/admin/products'
      path: '/products'
      fullPath: '/shop/admin/products'
      preLoaderRoute: typeof ShopAdminProductsRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/orders': {
      id: '/shop/admin/orders'
      path: '/orders'
      fullPath: '/shop/admin/orders'
      preLoaderRoute: typeof ShopAdminOrdersRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/inventory': {
      id: '/shop/admin/inventory'
      path: '/inventory'
      fullPath: '/shop/admin/inventory'
      preLoaderRoute: typeof ShopAdminInventoryRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/customers': {
      id: '/shop/admin/customers'
      path: '/customers'
      fullPath: '/shop/admin/customers'
      preLoaderRoute: typeof ShopAdminCustomersRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/categories': {
      id: '/shop/admin/categories'
      path: '/categories'
      fullPath: '/shop/admin/categories'
      preLoaderRoute: typeof ShopAdminCategoriesRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/shop/admin/analytics': {
      id: '/shop/admin/analytics'
      path: '/analytics'
      fullPath: '/shop/admin/analytics'
      preLoaderRoute: typeof ShopAdminAnalyticsRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/saas/auth/reset-password': {
      id: '/saas/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/saas/auth/reset-password'
      preLoaderRoute: typeof SaasAuthResetPasswordRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/auth/forgot-password': {
      id: '/saas/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/saas/auth/forgot-password'
      preLoaderRoute: typeof SaasAuthForgotPasswordRouteImport
      parentRoute: typeof SaasRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardPostsRoute: typeof DashboardPostsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTodosRoute: typeof DashboardTodosRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardPostsRoute: DashboardPostsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTodosRoute: DashboardTodosRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SaasRouteChildren {
  SaasBillingRoute: typeof SaasBillingRoute
  SaasOnboardingRoute: typeof SaasOnboardingRoute
  SaasSettingsRoute: typeof SaasSettingsRoute
  SaasTeamRoute: typeof SaasTeamRoute
  SaasUsageRoute: typeof SaasUsageRoute
  SaasIndexRoute: typeof SaasIndexRoute
  SaasAuthForgotPasswordRoute: typeof SaasAuthForgotPasswordRoute
  SaasAuthResetPasswordRoute: typeof SaasAuthResetPasswordRoute
}

const SaasRouteChildren: SaasRouteChildren = {
  SaasBillingRoute: SaasBillingRoute,
  SaasOnboardingRoute: SaasOnboardingRoute,
  SaasSettingsRoute: SaasSettingsRoute,
  SaasTeamRoute: SaasTeamRoute,
  SaasUsageRoute: SaasUsageRoute,
  SaasIndexRoute: SaasIndexRoute,
  SaasAuthForgotPasswordRoute: SaasAuthForgotPasswordRoute,
  SaasAuthResetPasswordRoute: SaasAuthResetPasswordRoute,
}

const SaasRouteWithChildren = SaasRoute._addFileChildren(SaasRouteChildren)

interface ShopAdminRouteChildren {
  ShopAdminAnalyticsRoute: typeof ShopAdminAnalyticsRoute
  ShopAdminCategoriesRoute: typeof ShopAdminCategoriesRoute
  ShopAdminCustomersRoute: typeof ShopAdminCustomersRoute
  ShopAdminInventoryRoute: typeof ShopAdminInventoryRoute
  ShopAdminOrdersRoute: typeof ShopAdminOrdersRoute
  ShopAdminProductsRoute: typeof ShopAdminProductsRoute
  ShopAdminReviewsRoute: typeof ShopAdminReviewsRoute
  ShopAdminIndexRoute: typeof ShopAdminIndexRoute
}

const ShopAdminRouteChildren: ShopAdminRouteChildren = {
  ShopAdminAnalyticsRoute: ShopAdminAnalyticsRoute,
  ShopAdminCategoriesRoute: ShopAdminCategoriesRoute,
  ShopAdminCustomersRoute: ShopAdminCustomersRoute,
  ShopAdminInventoryRoute: ShopAdminInventoryRoute,
  ShopAdminOrdersRoute: ShopAdminOrdersRoute,
  ShopAdminProductsRoute: ShopAdminProductsRoute,
  ShopAdminReviewsRoute: ShopAdminReviewsRoute,
  ShopAdminIndexRoute: ShopAdminIndexRoute,
}

const ShopAdminRouteWithChildren = ShopAdminRoute._addFileChildren(
  ShopAdminRouteChildren,
)

interface ShopOrdersRouteChildren {
  ShopOrdersIdRoute: typeof ShopOrdersIdRoute
}

const ShopOrdersRouteChildren: ShopOrdersRouteChildren = {
  ShopOrdersIdRoute: ShopOrdersIdRoute,
}

const ShopOrdersRouteWithChildren = ShopOrdersRoute._addFileChildren(
  ShopOrdersRouteChildren,
)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopAdminRoute: typeof ShopAdminRouteWithChildren
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrdersRoute: typeof ShopOrdersRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
  ShopAuthForgotPasswordRoute: typeof ShopAuthForgotPasswordRoute
  ShopAuthResetPasswordRoute: typeof ShopAuthResetPasswordRoute
  ShopCategoriesCategoryRoute: typeof ShopCategoriesCategoryRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopAdminRoute: ShopAdminRouteWithChildren,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrdersRoute: ShopOrdersRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
  ShopAuthForgotPasswordRoute: ShopAuthForgotPasswordRoute,
  ShopAuthResetPasswordRoute: ShopAuthResetPasswordRoute,
  ShopCategoriesCategoryRoute: ShopCategoriesCategoryRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface SupportAgentRouteChildren {
  SupportAgentCannedRoute: typeof SupportAgentCannedRoute
  SupportAgentRatingsRoute: typeof SupportAgentRatingsRoute
  SupportAgentIndexRoute: typeof SupportAgentIndexRoute
}

const SupportAgentRouteChildren: SupportAgentRouteChildren = {
  SupportAgentCannedRoute: SupportAgentCannedRoute,
  SupportAgentRatingsRoute: SupportAgentRatingsRoute,
  SupportAgentIndexRoute: SupportAgentIndexRoute,
}

const SupportAgentRouteWithChildren = SupportAgentRoute._addFileChildren(
  SupportAgentRouteChildren,
)

interface SupportCRouteChildren {
  SupportCIdRoute: typeof SupportCIdRoute
}

const SupportCRouteChildren: SupportCRouteChildren = {
  SupportCIdRoute: SupportCIdRoute,
}

const SupportCRouteWithChildren = SupportCRoute._addFileChildren(
  SupportCRouteChildren,
)

interface SupportRouteChildren {
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  SupportAgentRoute: typeof SupportAgentRouteWithChildren
  SupportCRoute: typeof SupportCRouteWithChildren
  SupportIndexRoute: typeof SupportIndexRoute
  SupportAuthForgotPasswordRoute: typeof SupportAuthForgotPasswordRoute
  SupportAuthResetPasswordRoute: typeof SupportAuthResetPasswordRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketIdRoute: SupportTicketIdRoute,
  SupportAgentRoute: SupportAgentRouteWithChildren,
  SupportCRoute: SupportCRouteWithChildren,
  SupportIndexRoute: SupportIndexRoute,
  SupportAuthForgotPasswordRoute: SupportAuthForgotPasswordRoute,
  SupportAuthResetPasswordRoute: SupportAuthResetPasswordRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SaasRoute: SaasRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
