<?php

declare(strict_types=1);

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * BetterAuth Authentication Test.
 *
 * Generated by BetterAuth. Run with: php artisan test --filter=BetterAuthTest
 */
final class BetterAuthTest extends TestCase
{
    use RefreshDatabase;

    private string $email = 'test@example.com';

    private string $password = 'SecurePassword123!';

    private string $name = 'Test User';

    /**
     * Test user can register.
     */
    public function test_user_can_register(): void
    {
        $response = $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $response->assertStatus(201)
            ->assertJsonStructure([
                'message',
                'user' => [
                    'id',
                    'email',
                    'name',
                ],
                'access_token',
                'refresh_token',
                'token_type',
                'expires_in',
            ]);

        $this->assertDatabaseHas('users', [
            'email' => $this->email,
        ]);
    }

    /**
     * Test user cannot register with invalid email.
     */
    public function test_user_cannot_register_with_invalid_email(): void
    {
        $response = $this->postJson('/auth/register', [
            'email' => 'not-an-email',
            'password' => $this->password,
        ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['email']);
    }

    /**
     * Test user cannot register with weak password.
     */
    public function test_user_cannot_register_with_weak_password(): void
    {
        $response = $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => 'short',
        ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['password']);
    }

    /**
     * Test user can login with valid credentials.
     */
    public function test_user_can_login_with_valid_credentials(): void
    {
        // First register a user
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        // Then login
        $response = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'user',
                'access_token',
                'refresh_token',
                'token_type',
                'expires_in',
            ]);
    }

    /**
     * Test user cannot login with invalid credentials.
     */
    public function test_user_cannot_login_with_invalid_credentials(): void
    {
        $response = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => 'wrong-password',
        ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['email']);
    }

    /**
     * Test authenticated user can access protected route.
     */
    public function test_authenticated_user_can_access_protected_route(): void
    {
        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $token = $loginResponse->json('access_token');

        // Access protected route
        $response = $this->withToken($token)
            ->getJson('/auth/me');

        $response->assertStatus(200)
            ->assertJson([
                'user' => [
                    'email' => $this->email,
                ],
            ]);
    }

    /**
     * Test unauthenticated user cannot access protected route.
     */
    public function test_unauthenticated_user_cannot_access_protected_route(): void
    {
        $response = $this->getJson('/auth/me');

        $response->assertStatus(401);
    }

    /**
     * Test user can refresh access token.
     */
    public function test_user_can_refresh_access_token(): void
    {
        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $refreshToken = $loginResponse->json('refresh_token');

        // Refresh token
        $response = $this->postJson('/auth/refresh', [
            'refresh_token' => $refreshToken,
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'access_token',
                'refresh_token',
                'token_type',
                'expires_in',
            ]);
    }

    /**
     * Test user cannot refresh with invalid token.
     */
    public function test_user_cannot_refresh_with_invalid_token(): void
    {
        $response = $this->postJson('/auth/refresh', [
            'refresh_token' => 'invalid-token',
        ]);

        $response->assertStatus(401);
    }

    /**
     * Test user can logout.
     */
    public function test_user_can_logout(): void
    {
        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $token = $loginResponse->json('access_token');
        $refreshToken = $loginResponse->json('refresh_token');

        // Logout
        $response = $this->withToken($token)->postJson('/auth/logout', [
            'refresh_token' => $refreshToken,
        ]);

        $response->assertStatus(200)
            ->assertJson([
                'message' => 'Logged out successfully',
            ]);
    }

    /**
     * Test user can revoke all tokens.
     */
    public function test_user_can_revoke_all_tokens(): void
    {
        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $token = $loginResponse->json('access_token');

        // Revoke all tokens
        $response = $this->withToken($token)
            ->postJson('/auth/revoke-all');

        $response->assertStatus(200)
            ->assertJson([
                'message' => 'All tokens revoked',
            ]);
    }

    /**
     * Test user can update password.
     */
    public function test_user_can_update_password(): void
    {
        $newPassword = 'NewSecurePassword456!';

        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $token = $loginResponse->json('access_token');

        // Update password
        $response = $this->withToken($token)
            ->putJson('/auth/password', [
                'current_password' => $this->password,
                'password' => $newPassword,
                'password_confirmation' => $newPassword,
            ]);

        $response->assertStatus(200)
            ->assertJson([
                'message' => 'Password updated successfully',
            ]);

        // Verify login with new password works
        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $newPassword,
        ]);

        $loginResponse->assertStatus(200);
    }

    /**
     * Test user cannot update password with wrong current password.
     */
    public function test_user_cannot_update_password_with_wrong_current_password(): void
    {
        // Register and login
        $this->postJson('/auth/register', [
            'email' => $this->email,
            'password' => $this->password,
            'name' => $this->name,
        ]);

        $loginResponse = $this->postJson('/auth/login', [
            'email' => $this->email,
            'password' => $this->password,
        ]);

        $token = $loginResponse->json('access_token');

        // Try to update with wrong current password
        $response = $this->withToken($token)
            ->putJson('/auth/password', [
                'current_password' => 'wrong-password',
                'password' => 'NewSecurePassword456!',
                'password_confirmation' => 'NewSecurePassword456!',
            ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['current_password']);
    }
}
